# Generated by Django 5.2.7 on 2025-10-15 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("place", models.CharField(max_length=100)),
                ("time", models.TimeField()),
                ("action", models.CharField(max_length=200)),
                ("is_pleasant", models.BooleanField(default=False)),
                ("periodicity", models.PositiveSmallIntegerField(default=1)),
                ("reward", models.CharField(blank=True, max_length=200, null=True)),
                ("duration", models.PositiveSmallIntegerField()),
                ("is_public", models.BooleanField(default=False)),
                (
                    "related_habit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="habits.habit",
                    ),
                ),
            ],
        ),
    ]
